language: java

jdk:
  - oraclejdk8

install:
  - wget http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar xzf apache-maven-3.3.9-bin.tar.gz
  - chmod +x $PWD/apache-maven-3.3.9/bin/mvn

script:
  - ls -l $PWD/apache-maven-3.3.9/bin
  - export PATH=$PWD/apache-maven-3.3.9/bin:$PATH
  - mvn clean package
