language: java

jdk:
  - oraclejdk8

install:
  - curl http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz | tar xz
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:$PATH

script:
  - mvn -v
  - $PWD/apache-maven-3.3.9/bin/mvn -v
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - $PWD/apache-maven-3.3.9/bin/mvn -v
  - $PWD/apache-maven-3.3.9/bin/mvn clean package
